### ISSUE TITLE
Race in isTTY?

### ISSUE THREAD

**Issue by ammario** [coder/slog#176]
We just saw [this data race in coder/coder](https://github.com/coder/coder/actions/runs/5124900108/jobs/9217443005#step:9:337). 

I'm assuming it was introduced here https://github.com/coder/slog/pull/167, but haven't thoroughly investigated.

**Comment by mafredri** [comment]
@ammario It's the opposite, the issue was fixed in https://github.com/coder/slog/pull/167 and due to the revert, this issue became much more prevalent.

The problem must be that an `os.File` was wrapped without implementing `SyscallConn` and passed to `entryhuman`, which used the old behavior of `.Fd` which is unsafe.

**Comment by mafredri** [comment]
Actually, perhaps the fix in #167 was incomplete, it seems syncwriter always(?) wraps the writer, but does not implement `SyscallConn`, so the fix was never effective and reverted to the old unsafe behavior.

**Comment by mafredri** [comment]
The actual issue is that #167 wasn't used. The linked error shows `slog` v1.5.3 being used. #167 wasn't merged until v1.5.4.

**Comment by ammario** [comment]
Ok.. So revert the revert?

**Comment by coadler** [comment]
Unreverted by #187
